
../bin/x86/linux/threads: threads.cpp
	g++ -o ../bin/x86/linux/threads threads.cpp -pthread -std=c++11

../bin/arm/linux/threads: threads.cpp
	g++ -o ../bin/arm/linux/threads threads.cpp -pthread -std=c++11
