#!/bin/bash

# requires docker, sudo apt install docker.io

set -e
set -u

if [ -z "$(docker images -q gem5-dev 2> /dev/null)" ]; then
    docker build \
        --file util/dockerfiles/ubuntu-24.04_all-dependencies/Dockerfile \
        --tag gem5-dev \
        .
fi

THISDIR=$(pwd -P)

docker run \
    --interactive \
    --tty \
    --user $(id -u):$(id -g) \
    --network host \
    --env HOME=$HOME \
    -v $HOME:$HOME \
    -v $THISDIR:$THISDIR \
    --workdir $THISDIR \
    --rm \
    gem5-dev \
    $*
